### ISSUE TITLE
Does this repo control the package on npmjs.com?

### ISSUE THREAD

**Issue by roydukkey** [ChadKillingsworth/closure-compiler-npm#1]
It seems the versions are out of sync? https://www.npmjs.com/package/google-closure-compiler

**Comment by ChadKillingsworth** [comment]
This publishes the beta versions currently. As soon as a new version of the compiler is released (possibly tomorrow), this will be the production version.

You can install this version with `npm install google-closure-compiler@beta`

**Comment by ChadKillingsworth** [comment]
To further clarify, the compiler.jar contained in this version has features that have yet to be officially released. They were specifically written to support node build systems. See google/closure-compiler#1253

**Comment by ChadKillingsworth** [comment]
This was just published as the official release.
