### ISSUE TITLE
Java options

### ISSUE THREAD

**Issue by trofim24** [ChadKillingsworth/closure-compiler-npm#15]
How to pass arguments to Java ( Java options, eg Xms2048m) ?
When closure compiler startup falls outOfMemoryError.

**Comment by ChadKillingsworth** [comment]
It's not currently covered, though it could be added pretty easily. I started to handle this case initially, but found that most arguments were obsoleted by newer versions of Java. I'll see if I can add an option.

**Comment by trofim24** [comment]
It would be great.
It would be possible to add an option to insert items in the beginning `commandArguments` array or some other method.
