### ISSUE TITLE
Install instructions incorrect

### ISSUE THREAD

**Issue by priceaj** [ChadKillingsworth/closure-compiler-npm#2]
Running npm install --save google-closure-compiler installs https://github.com/google/closure-compiler

**Comment by ChadKillingsworth** [comment]
This is correct. This repo [is in beta right now](https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/package.json#L10). As soon as the next version of closure-compiler is released, the beta tag will be removed and this will become the repo managing npm deployment. I anticipate this happening within the next week.

Until then, install with `npm install --save google-closure-compiler@beta`

**Comment by ChadKillingsworth** [comment]
Also, see #1

**Comment by ChadKillingsworth** [comment]
This was just published as the official release.
