### ISSUE TITLE
Specifing java path as option.

### ISSUE THREAD

**Issue by firecow** [ChadKillingsworth/closure-compiler-npm#22]
Hey Chad.

Would it be possible to specify java path as an option.
We have a build environment, where we have many different java versions.
It would be awesome for us to be able to pinpoint exactly what executable to use.

Yours
   Mads

**Comment by ChadKillingsworth** [comment]
I think you should be able to do that like so:

```js
const compiler = require('google-closure-compiler/lib/node/closure-compiler');
compiler.prototype.javaPath = '/foo/bar';
```

**Comment by firecow** [comment]
I'm using your gulp file.
Would it be possible to specify the javapath in gulps initOptions?

```
gulp/index.js
module.exports = function(initOptions) {

}

Where initOptions could take 
{
  "javaPath": /usr/lib/jvm/java-8-oracle/jre/bin/java
}
```

**Comment by firecow** [comment]
I've sent you a pullrequest, where i've added javaPath to gulp initOptions.

**Comment by ChadKillingsworth** [comment]
Sorry - let me be clearer. You can still use gulp. Here's a snippet with more context:

```js
const compiler = require('google-closure-compiler/lib/node/closure-compiler');
compiler.prototype.javaPath = '/foo/bar/java';

const closureCompiler = require('google-closure-compiler').gulp();

gulp.task('js-compile', function () {
  return gulp.src('./src/js/**/*.js', {base: './'})
      .pipe(closureCompiler({
          compilation_level: 'SIMPLE',
          warning_level: 'VERBOSE',
        }))
      .pipe(gulp.dest('./dist/js'));
});

```

**Comment by ChadKillingsworth** [comment]
I tested this and got the desired behavior. If the above snippet doesn't work for you, feel free to reopen.
