### ISSUE TITLE
Output mangled

### ISSUE THREAD

**Issue by surma** [ChadKillingsworth/closure-compiler-npm#24]
(I am not 100% sure this is a closure issue.)

Here’s an example gulp script:
```js
#!/usr/bin/env node

const gulp = require('gulp');
const closure = require('google-closure-compiler').gulp();
const fs = require('fs');

gulp.task('compile', _ => {
  return gulp.src('testfile.js')
    .pipe(closure({
      conformance_configs: 'closure/conformance_config.textproto'
    }))
    .on('error', error => {
      fs.writeFileSync('error.log', error);
    })
});

gulp.start('compile');
```

If I run this on macOS, the output gets mangled (cut-off mid console dump):
![screenshot 2016-07-07 13 29 23](https://cloud.githubusercontent.com/assets/234957/16653117/dfa4aaa4-4446-11e6-8cfc-0908fd698d0b.png)

The `error.log` file contains the full error message. 

This error does not seem to occur on Linux and is independent of the shell (tested zsh and bash).

**Comment by ChadKillingsworth** [comment]
Was this caused because the file didn't exist or because it had a syntax error? I can recreate the issue pretty easily since I develop on a Mac.

**Comment by surma** [comment]
Afaict, any kind of error suffers from getting mangled.

My example code errors because the conformance config does not exist, yes :)

**Comment by ChadKillingsworth** [comment]
I'm looking at this and I definitely don't see the same behavior. I can make some guesses, but it's hard to test this without being able to reproduce it.

![screen shot 2016-07-18 at 2 19 29 pm](https://cloud.githubusercontent.com/assets/1247639/16927403/c7cb08a6-4cf2-11e6-98dc-2f87610210de.png)

What node version are you using?

**Comment by surma** [comment]
I am at node 6.3. 

In the mean time I have found out that `&> log.txt` yields unmangled output.. Apparently, `stdout` is buffered, while pipes are not. 

Saying that made me realize that I am convinced that this is a node or macOS issue and not specific to closure-compiler. So feel free to close.

**Comment by ChadKillingsworth** [comment]
My thought was to add a `process.nextTick` wrapper to account for this. Let me see what I can come up with and let your try it.

**Comment by surma** [comment]
I actually tried adding a `setTimeout` before closing the stream (on gulp level) – didn’t help the cause. But feel free to send me things to try :) I am very intrigued by this problem.

**Comment by ChadKillingsworth** [comment]
This is purely a guess, but see if this happens to work: https://github.com/ChadKillingsworth/closure-compiler-npm/compare/master...wait-for-stderr

**Comment by surma** [comment]
Yes, that seems to fix it on my side!
