### ISSUE TITLE
v20160713 changes affecting builds

### ISSUE THREAD

**Issue by pzula** [ChadKillingsworth/closure-compiler-npm#25]
We noticed that with the newest release of `google-closure-complier` added the version number in the filename of the `jar` file. This is causing builds to fail when using `closure-complier` to fail on builds with the following warning:

```
Warning: Error: Unable to access jarfile [full path was here]/node_modules/grunt-closurecompiler/node_modules/closurecompiler/compiler/compiler.jar
 Use --force to continue.
```

Would love to help debug, but not sure where to start 😃  Currently this is affecting our production builds, so would love to get this resolved. If you can point me in the right direction, that would be rad!

**Comment by ChadKillingsworth** [comment]
That's not our plugin ... it's actually https://github.com/dcodeIO/grunt-closurecompiler and it hasn't been updated in 3 years. It's making use of this plugin: https://github.com/tim-smart/node-closure - also not ours (and also very old).

I suggest you update to this plugin and use the grunt task that is included. It's not a direct replacement (you'll have to tweak your grunt config), but is was specifically designed to lower some of the pain points existing plugins had.

This package is part of the official release cycle of closure-compiler and has test coverage to prevent problems like this.

**Comment by ChadKillingsworth** [comment]
FYI if you have questions or trouble switching, feel free to post here. I try to be pretty responsive.

**Comment by MatrixFrog** [comment]
Chad, I think you missed pasting a link maybe?

**Comment by ChadKillingsworth** [comment]
@MatrixFrog What link? This one maybe? https://www.npmjs.com/package/google-closure-compiler
