### ISSUE TITLE
NO Access to compiler.jar on the Latest Release 20160713.0.0

### ISSUE THREAD

**Issue by 8bamo** [ChadKillingsworth/closure-compiler-npm#29]
Is there a specific reason why you renamed the compiler.jar ?

I cant access the compiler.jar cause its renamed into a prefixed version with a version number at the end of the name.

Can you please rename the file into compiler.jar back?

**Comment by ChadKillingsworth** [comment]
We didn't rename the compiler.jar. Are you sure you are using the correct package? Our package is named [`google-closure-compiler`](https://www.npmjs.com/package/google-closure-compiler). See #25 - we have had reports that other packages not maintained by the Closure-Compiler team may be broken.

**Comment by MatrixFrog** [comment]
If you're getting the compiler from dl.google.com, we did rename it. This is in the release notes and was announced at https://groups.google.com/forum/#!topic/closure-compiler-discuss/7VyMemWKqdg

If you're getting it from the official npm package, everything should be the same as before, as Chad says.

**Comment by concavelenz** [comment]
I missed this. Why did we rename it? That seems like it would cause folks
unnecessary pain.

**Comment by MatrixFrog** [comment]
It simplifies our release process. If it causes pain a lot of pain we can rename it back to compiler.jar for the next release.

**Comment by ChadKillingsworth** [comment]
So far, the only reports have been from npm plugins that pre-date our official grunt/gulp plugins. I have no problem breaking plugins that haven't been updated in 3 years.
