### ISSUE TITLE
Usage with buffers

### ISSUE THREAD

**Issue by gmadar** [ChadKillingsworth/closure-compiler-npm#39]
Can the module get an input of a buffer (or a content string, not a file name) 
and produce a buffer (or the optimized result as a string)?

If the answer is yes - can someone please provide a code sample on how to do that?

**Comment by ChadKillingsworth** [comment]
This is much easier with the JS version of the compiler: https://github.com/google/closure-compiler-js

It's possible to with the java version, but I don't have any examples written. The [gulp tests](https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/test/gulp.js) do this to some degree.

**Comment by Autre31415** [comment]
Now that closure-compiler-js has been deprecated, it is now possible to output a content string here like we could in the previous module?
