### ISSUE TITLE
Use peer dependencies for gulp-util

### ISSUE THREAD

**Issue by evmar** [ChadKillingsworth/closure-compiler-npm#41]
https://nodejs.org/en/blog/npm/peer-dependencies/ describes how when you're providing a plugin for gulp, you should use a peer dependency rather than a strict dependency.

Doing this would let me use google-closure-compiler from a project that doesn't involve gulp without needing to install all the gulp dependencies when I use it.

**Comment by ChadKillingsworth** [comment]
Peer dependencies were significantly changed in npm 3. They are no longer automatically installed.
