### ISSUE TITLE
No documentation for passing in existing source map?

### ISSUE THREAD

**Issue by QuantumRevenger** [ChadKillingsworth/closure-compiler-npm#45]
I can find documentation for creating a source map, but how do I provide an existing one? (UglifyJS supports this to remap)

**Comment by ChadKillingsworth** [comment]
Gulp or Grunt?

**Comment by QuantumRevenger** [comment]
Node.JS though I am looking into a suggestion from another dev to use https://github.com/azu/multi-stage-sourcemap and merge the time-being.

**Comment by ChadKillingsworth** [comment]
Then you'll be using the built in compiler flags. It looks like we missed documented the flag from the CLI. Here's the input flag: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L314-L318

In addition, you'll want this flag: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L326-L331 It is new in the 20160911 release, but defaults to `false`. It will default to `true` in the next release.

You can also compose source maps in JavaScript. Here's how: https://github.com/ChadKillingsworth/closure-compiler-npm/blob/2d7d66d730738e62edef5abb4773caafb3a478c4/lib/gulp/index.js#L178-L191
Compared to the compiler doing it natively, JS is very slow. As soon as the next release lands, the gulp plugin will use the builtin compiler options.
