### ISSUE TITLE
[Request] Separate grunt and gulp plugins from core

### ISSUE THREAD

**Issue by teppeis** [ChadKillingsworth/closure-compiler-npm#47]
I don't use grunt and gulp, but this includes them.
They significantly increase file size.

Can you separate them to other package?

**Comment by ChadKillingsworth** [comment]
We bundled them together very intentionally. With npm, it's very hard to manage the compiler version separate from the plugins. Most users care most about the compiler version and just want the working plugin version.

Also, future work will further integrate the functionality. Grunt already uses the gulp plugin internally.

**Comment by teppeis** [comment]
@ChadKillingsworth 

> With npm, it's very hard to manage the compiler version separate from the plugins. Most users care most about the compiler version and just want the working plugin version.

Yes, and monorepo with `lerna` is a solution for the situation.
This is my fork using lerna.
https://github.com/teppeis/closure-compiler-npm/tree/monorepo

You can publish all packages with `lerna publish` at a time and there are no breaking changes for existing users.
The current `google-closure-compiler` package has 237 dependencies in production, but new `google-closure-compiler-jar` has nothing. The 237 packages are unnecessary for non-gulp/grunt users like webpack plugins or full-scratch tool.

If this is interesting, I'll send a pull-request.

**Comment by ChadKillingsworth** [comment]
We really don't want to maintain extra packages right now.

However the dependencies were somewhat out-of-control. I've PR'd a change to improve the situation.

**Comment by teppeis** [comment]
@ChadKillingsworth Thanks! It's reasonable improvement.
